export const slidersMocDat = [
  {
    id: 7802208,
    imageUrl: "https://podspace.pod.ir/api/images/KKMHI2NV8BZ1CK3N",
    smallImageUrl: "https://podspace.pod.ir/api/images/YDTMBV48CC1UCDE9",
    mediumImageUrl: "https://podspace.pod.ir/api/images/U6UDJIVJ1GCZS9DM",
    logoImageUrl: "https://podspace.pod.ir/api/images/BI8LKMFNZ8FWTB2P",
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 7802124,
    imageUrl: "https://podspace.pod.ir/api/images/WFB56VRWMVS9U75U",
    smallImageUrl: "https://podspace.pod.ir/api/images/WEEXKQLBDZ7SSKAB",
    mediumImageUrl: "https://podspace.pod.ir/api/images/6OSDHW4Z3FJTKQWR",
    logoImageUrl: "https://podspace.pod.ir/api/images/LSJW62LEQMO5LWE7",
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 7769718,
    imageUrl: "https://podspace.pod.ir/api/images/9AEIES5XGDSVPN9H",
    smallImageUrl: "https://podspace.pod.ir/api/images/49M2S28S4TZHS9MV",
    mediumImageUrl: "https://podspace.pod.ir/api/images/6T1Y8I8F8HA98HTO",
    logoImageUrl: "https://podspace.pod.ir/api/images/6O5X34WHYPH1IFEF",
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 7769685,
    imageUrl: "https://podspace.pod.ir/api/images/VMSWLTTCCO6WSGUJ",
    smallImageUrl: "https://podspace.pod.ir/api/images/RZAJ7N9UYC7G67RJ",
    mediumImageUrl: "https://podspace.pod.ir/api/images/EI5D1BAKFHA3TDHW",
    logoImageUrl: "https://podspace.pod.ir/api/images/TJIGCT8P61Y7A3MP",
    type: "post",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 7769639,
    imageUrl: "https://podspace.pod.ir/api/images/19XHIPI18OIIC3OG",
    smallImageUrl: "https://podspace.pod.ir/api/images/2ENPJEW5USJOE5TJ",
    mediumImageUrl: "https://podspace.pod.ir/api/images/22URJ23ZOO5F3KH3",
    logoImageUrl: "https://podspace.pod.ir/api/images/938UXIX17FLJTFOW",
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 6772462,
    imageUrl: "https://podspace.pod.ir/api/images/KKMHI2NV8BZ1CK3N",
    smallImageUrl: null,
    mediumImageUrl: null,
    logoImageUrl: null,
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 6711556,
    imageUrl: "https://podspace.pod.ir/api/images/WFB56VRWMVS9U75U",
    smallImageUrl: null,
    mediumImageUrl: null,
    logoImageUrl: null,
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 6711546,
    imageUrl: "https://podspace.pod.ir/api/images/9AEIES5XGDSVPN9H",
    smallImageUrl: null,
    mediumImageUrl: null,
    logoImageUrl: null,
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: null,
    entityType: null,
  },
  {
    id: 6689202,
    imageUrl: "https://podspace.pod.ir/api/images/VMSWLTTCCO6WSGUJ",
    smallImageUrl: null,
    mediumImageUrl: null,
    logoImageUrl: null,
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: 19552992,
    entityType: "series-content",
  },
  {
    id: 6626554,
    imageUrl: "https://podspace.pod.ir/api/images/19XHIPI18OIIC3OG",
    smallImageUrl: null,
    mediumImageUrl: null,
    logoImageUrl: null,
    type: "none",
    buttonTitle: null,
    link: null,
    entityId: 19267814,
    entityType: "series-content",
  },
];
